[build]
  command = "npm run build"
  publish = "dist"

# Pin Node version for Netlify builds
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200